version: "3"

services:
  server:
    build: .
    command: yarn dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
